### ISSUE TITLE
Incomplete preprocessed desc data

### ISSUE THREAD

**Issue by Yaozhuwa** [danqu130/RPEFlow#1]
I download the preprocessed desc dataset via https://drive.google.com/drive/folders/1p-gz3HcR6bp65Ms6IGaHCIhAPwOXQ_LE ,and 
![image](https://github.com/danqu130/RPEFlow/assets/28787183/9c6b5edd-2676-4ced-b67c-b164967a7420)

I test the dataloader using code below:
```python
    import yaml
    from omegaconf import DictConfig, OmegaConf
    with open('conf/train/dsec.yaml', encoding='utf-8') as f:
        cfgs = DictConfig(yaml.load(f, Loader=yaml.FullLoader))
    train_dataset = DSECPreprocessTrain(cfgs.trainset)
    sample1 = train_dataset[0]
    print('Done!')
```
in https://github.com/danqu130/RPEFlow/blob/e5a9c0ec1d2fdaddd51aa8b6569b801ce94ee690/dsec.py#L616
raise error: KeyError: "Unable to synchronously open object (object 'event_voxel' doesn't exist)"

so I check the hdf5file, and print all of the hdf5file.keys:
 ```
<KeysViewHDF5 ['disp1', 'disp2', 'events_p', 'events_t', 'events_x', 'events_y', 'flow12', 'flow12_valid', 'flow21', 'flow21_valid', 'image1', 'image2', 'intrinsics', 'perspectives']>
```
It doesn't have key of 'voxel grid'

**Comment by danqu130** [comment]
I apologize that I was reminded a few days ago that the previously uploaded version was incorrect. I have completed the correct upload and suggest you re-download it. e5a9c0ec1d2fdaddd51aa8b6569b801ce94ee690

Just a few moments ago, I rechecked and the new zip contains the correct data.

Here's a link to the aliyundrive, but its limited to only 24 hours of validity, and the only difference between it and Google Cloud Drive is not stored in zip chunks.
https://www.aliyundrive.com/t/fT795aVR54uzvXjEVF5G

**Comment by Yaozhuwa** [comment]
Sorry, I check the issue too late to download the new link. Could you please share it once again?

By the way, I found a function `eventToVoxelInter` to solve this issue (use the provided events to obtain voxel grids between frame1 and frame2), but I don't kown if it's right. Code is below:
```python
image1, image2, events, flow_2d, flow_2d_mask, \
            disp1, disp2, intrinsics, perspectives = self.open_hdf5(self.preprocess_list[index])
image_h, image_w = image1.shape[:2]
event_voxel = self.eventsToVoxelInter(
events, num_bins=self.event_bins, height=image_h, width=image_w,
event_polarity=self.event_polarity
)
```

## An other issue is that I found test split of the processed DSEC dataset only provide limited data:
```
<KeysViewHDF5 ['events_p', 'events_t', 'events_x', 'events_y', 'image1', 'image2']>
```
So I can't evaluate my model.

**Comment by danqu130** [comment]
1. Here's a new link to the aliyundrive, but its also limited to only 24 hours of validity. 
https://www.aliyundrive.com/t/Sv1bACKVNKqLPUhGzLg2

The only difference between it and Google Cloud Drive is not stored in zip chunks. You still have the option to download from Google Cloud Drive.

2. You are correct about voxelizing the events. But I'm not sure if the event data in the wrong data that was previously shared is correct.

4. The data you previously downloaded was wrong, I just processed the test set into hdf5 format. Since I could not compute the scene flow trues for the test set, I did not use it, so there is no test set in the newly uploaded zip. As shown in the paper and code, I split the DSEC training set into training and validation sets. All metrics in the paper are reported on the validation set.
https://github.com/danqu130/RPEFlow/blob/main/dsec.py#L207

**Comment by Yaozhuwa** [comment]
Thank you very much for your patient answer~

### missing raw event data in Flyingthings_processed dataset
For the Flyingthings_processed dataset, the HDF5 files do not provide the **raw event data**, which limits the possibilities for exploring certain **event representation** methods in this dataset. Could you please provide the **raw event data**?

### baseline of Flyingthings_processed dataset
Additionally, what is the baseline used for computing depth in the Flyingthings3d dataset?

**Comment by danqu130** [comment]
1. The raw event data size is large and I haven't uploaded it yet. I suggest you simulate it using esim_py. If you still need it, please let me know and give me some time to upload it to aliyun. 
2. As mentioned in the README, please refer to the point cloud generation code from CamLiFlow.
https://github.com/MCG-NJU/CamLiFlow/blob/main/preprocess_flyingthings3d_subset.py#L76

**Comment by Yaozhuwa** [comment]
> The raw event data size is large and I haven't uploaded it yet. I suggest you simulate it using esim_py. If you still need it, please let me know and give me some time to upload it to aliyun.

I would greatly appreciate it if you could provide the the Flyingthings raw event data.

Thank you very much!

**Comment by danqu130** [comment]
I have completed uploading the simulated event data. Here's a link to the aliyundrive, but its also limited to only 24 hours of validity.
https://www.aliyundrive.com/t/ngDcrkpWrrcxTXQeNsDG

**Comment by danqu130** [comment]
I'm closing this issue now, if there are any further problems please feel free to post them.
