### ISSUE TITLE
File structure of EKubric dataset

### ISSUE THREAD

**Issue by CheungBH** [danqu130/RPEFlow#2]
Hi. Thanks for your great work. 
I am currently running your code with EKubric dataset. Due to the limitation of disk storage, I only downloaded "sf_preprocess.z04". However, I am not sure how to place the dataset correctly.

I tried "./datasets/ekubric/sf_preprocess/sf_preprocess.z04", and it reported "assert os.path.isdir(seq_path) AssertionError". When I put the sequence into an inner folder like "./datasets/ekubric/sf_preprocess/val/sf_preprocess.z04", it reports "ValueError: invalid literal for int() with base 10: 'sf'".

I wonder how to place the sequence?

**Comment by danqu130** [comment]
The dataset is large and you need to download all the zip archives separately, place them together and unzip sf_preprocess.zip.
```
unzip sf_preprocess.zip
```
Then place the sf_preprocess folder inside dataset/ekubric/
```
dataset/ekubric/
├── sf_preprocess
```

The total size of these zips is 143G and the unzipped folder size is 147G. I can provide the aliyun drive share link for the single zip version if you need it.
